export default [
  {
    basePath: '/api/admin/forex',
    controllerPath: './extensions/forex/admin/controller',
    routes: [
      {
        method: 'get',
        path: '',
        controller: 'index',
        permission: 'Access Forex Management',
      },
    ],
  },
  {
    basePath: '/api/forex/account',
    controllerPath: './extensions/forex/accounts/controller',
    routes: [
      {
        method: 'get',
        path: '',
        controller: 'index',
      },
      {
        method: 'get',
        path: '/:id',
        controller: 'show',
        params: ['id'],
      },
      {
        method: 'post',
        path: '/:id/deposit',
        controller: 'deposit',
        params: ['id'],
        body: ['walletUuid', 'amount'],
      },
      {
        method: 'post',
        path: '/:id/withdraw',
        controller: 'withdraw',
        params: ['id'],
        body: ['currency', 'amount'],
      },
    ],
  },
  {
    basePath: '/api/admin/forex/accounts',
    controllerPath: './extensions/forex/admin/accounts/controller',
    routes: [
      {
        method: 'get',
        path: '',
        controller: 'index',
        permission: 'View Forex Accounts',
      },
      {
        method: 'get',
        path: '/:id',
        controller: 'show',
        params: ['id'],
        permission: 'View Forex Accounts',
      },
      {
        method: 'post',
        path: '',
        controller: 'create',
        body: [
          'account_id',
          'password',
          'mt',
          'broker',
          'type',
          'status',
          'balance',
          'leverage',
        ],
        permission: 'Create Forex Accounts',
      },
      {
        method: 'put',
        path: '/:id',
        controller: 'update',
        params: ['id'],
        body: [
          'account_id',
          'password',
          'mt',
          'broker',
          'type',
          'status',
          'balance',
          'leverage',
        ],
        permission: 'Edit Forex Accounts',
      },
      {
        method: 'del',
        path: '/:id',
        controller: 'delete',
        params: ['id'],
        permission: 'Delete Forex Accounts',
      },
    ],
  },
  {
    basePath: '/api/admin/forex/transactions',
    controllerPath: './extensions/forex/admin/transactions/controller',
    routes: [
      {
        method: 'get',
        path: '',
        controller: 'index',
        permission: 'View Forex Transactions',
      },
      {
        method: 'get',
        path: '/:id',
        controller: 'show',
        params: ['id'],
        permission: 'View Forex Transactions',
      },
      {
        method: 'put',
        path: '/:uuid',
        controller: 'update',
        params: ['uuid'],
        body: ['status', '?message'],
        permission: 'View Forex Transactions',
      },
    ],
  },
  {
    basePath: '/api/forex/investments',
    controllerPath: './extensions/forex/investments/controller',
    routes: [
      {
        method: 'get',
        path: '',
        controller: 'index',
      },
      {
        method: 'get',
        path: '/active/investment',
        controller: 'active',
      },
      {
        method: 'get',
        path: '/:id',
        controller: 'status',
        params: ['id'],
      },
      {
        method: 'post',
        path: '',
        controller: 'create',
        body: ['accountId', 'planId', 'durationId', 'amount'],
      },
      {
        method: 'post',
        path: '/:id/cancel',
        controller: 'cancel',
        params: ['id'],
      },
    ],
  },
  {
    basePath: '/api/cron/forex/investment',
    controllerPath: './extensions/forex/investments/controller',
    routes: [
      {
        method: 'get',
        path: '',
        controller: 'cron',
        isGuest: true,
      },
    ],
  },
  {
    basePath: '/api/forex/plans',
    controllerPath: './extensions/forex/plans/controller',
    routes: [
      {
        method: 'get',
        path: '',
        controller: 'index',
      },
    ],
  },
  {
    basePath: '/api/admin/forex/investments',
    controllerPath: './extensions/forex/admin/investments/controller',
    routes: [
      {
        method: 'get',
        path: '',
        controller: 'index',
        permission: 'View Forex Investments',
      },
      {
        method: 'get',
        path: '/:id',
        controller: 'show',
        params: ['id'],
        permission: 'View Forex Investments',
      },
      {
        method: 'put',
        path: '/:id',
        controller: 'update',
        params: ['id'],
        body: ['profit', 'result'],
        permission: 'Edit Forex Investments',
      },
      {
        method: 'del',
        path: '/:id',
        controller: 'delete',
        params: ['id'],
        permission: 'Delete Forex Investments',
      },
    ],
  },
  {
    basePath: '/api/admin/forex/plans',
    controllerPath: './extensions/forex/admin/plans/controller',
    routes: [
      {
        method: 'get',
        path: '',
        controller: 'index',
        permission: 'View Forex Plans',
      },
      {
        method: 'get',
        path: '/:id',
        controller: 'show',
        params: ['id'],
        permission: 'View Forex Plans',
      },
      {
        method: 'post',
        path: '',
        controller: 'create',
        body: ['plan'],
        permission: 'Create Forex Plans',
      },
      {
        method: 'put',
        path: '/:id',
        controller: 'update',
        params: ['id'],
        body: ['plan'],
        permission: 'Edit Forex Plans',
      },
      {
        method: 'del',
        path: '/:id',
        controller: 'delete',
        params: ['id'],
        permission: 'Delete Forex Plans',
      },
    ],
  },
  {
    basePath: '/api/admin/forex/durations',
    controllerPath: './extensions/forex/admin/durations/controller',
    routes: [
      {
        method: 'get',
        path: '',
        controller: 'index',
        permission: 'View Forex Durations',
      },
      {
        method: 'get',
        path: '/:id',
        controller: 'show',
        params: ['id'],
        permission: 'View Forex Durations',
      },
      {
        method: 'post',
        path: '',
        controller: 'create',
        body: ['duration'],
        permission: 'Create Forex Durations',
      },
      {
        method: 'put',
        path: '/:id',
        controller: 'update',
        params: ['id'],
        body: ['duration'],
        permission: 'Edit Forex Durations',
      },
      {
        method: 'del',
        path: '/:id',
        controller: 'delete',
        params: ['id'],
        permission: 'Delete Forex Durations',
      },
    ],
  },
  {
    basePath: '/api/admin/forex/signals',
    controllerPath: './extensions/forex/admin/signals/controller',
    routes: [
      {
        method: 'get',
        path: '',
        controller: 'index',
        permission: 'View Forex Signals',
      },
      {
        method: 'get',
        path: '/:id',
        controller: 'show',
        params: ['id'],
        permission: 'View Forex Signals',
      },
      {
        method: 'post',
        path: '',
        controller: 'create',
        body: ['title', 'image', 'status'],
        permission: 'Create Forex Signals',
      },
      {
        method: 'put',
        path: '/:id',
        controller: 'update',
        params: ['id'],
        body: ['title', 'image', 'status'],
        permission: 'Edit Forex Signals',
      },
      {
        method: 'del',
        path: '/:id',
        controller: 'delete',
        params: ['id'],
        permission: 'Delete Forex Signals',
      },
    ],
  },
  {
    basePath: '/api/admin/forex/currencies',
    controllerPath: './extensions/forex/admin/currencies/controller',
    routes: [
      {
        method: 'get',
        path: '',
        controller: 'index',
        permission: 'View Forex Currencies',
      },
      {
        method: 'get',
        path: '/:id',
        controller: 'show',
        params: ['id'],
        permission: 'View Forex Currencies',
      },
      {
        method: 'post',
        path: '',
        controller: 'create',
        body: ['currency'],
        permission: 'Create Forex Currencies',
      },
      {
        method: 'put',
        path: '/:id',
        controller: 'update',
        params: ['id'],
        body: ['currency'],
        permission: 'Edit Forex Currencies',
      },
      {
        method: 'del',
        path: '/:id',
        controller: 'delete',
        params: ['id'],
        permission: 'Delete Forex Currencies',
      },
    ],
  },
]
